#!/bin/bash

MIRRORS_LOCATION=Germany

HOSTNAME=ArchBlue

# CHANGE TO YOUR DRIVE!
DRIVE=/dev/vda
DRIVE_BOOTABLE=/dev/vda1
DRIVE_SYSTEM=/dev/vda2

echo "---------------------------------------------"
echo "OPTIMIZING MIRRORLIST"
echo "---------------------------------------------"

pacman -Syyy
pacman -S reflector
reflector -c $MIRRORS_LOCATION -a 10 --sort rate --save /etc/pacman.d/mirrorlist
pacman -Syyy

echo "---------------------------------------------"
echo "CREATING PARTITIONS"
echo "---------------------------------------------"

sgdisk --zap-all $DRIVE
sleep 1
cfdisk $DRIVE
sleep 1

echo "---------------------------------------------"
echo ""
echo "---------------------------------------------"

cryptsetup --verbose --cipher aes-xts-plain64 --key-size 512 --hash sha512 --iter-time 5000 --use-random luksFormat $DRIVE_SYSTEM
sleep 1
cryptsetup open --type luks $DRIVE_SYSTEM cryptroot
sleep 1
mkfs.ext4 $DRIVE_BOOTABLE
sleep 1
mkfs.ext4 /dev/mapper/cryptroot
sleep 1
mount -t ext4 /dev/mapper/cryptroot /mnt
sleep 1
mkdir -p /mnt/boot
sleep 1
mount -t ext4 $DRIVE_BOOTABLE /mnt/boot
sleep 1
pacstrap -i /mnt base base-devel linux linux-firmware neovim wget
sleep 1
genfstab -U -p /mnt >> /mnt/etc/fstab
sleep 1
arch-chroot /mnt
