#!/bin/bash

USERNAME=tomas
DRIVE=/dev/vda

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sleep 1
locale-gen
sleep 1
echo LANG=en_US.UTF-8 > /etc/locale.conf
sleep 1
export LANG=en_US.UTF-8
sleep 1
ln -s /usr/share/zoneinfo/Europe/Prague /etc/localtime
sleep 1
hwclock --systohc --utc
sleep 1
echo $HOSTNAME > /etc/hostname
sleep 1
passwd
sleep 1
useradd -m -g users -G wheel,games,power,optical,storage,scanner,lp,audio,video -s /bin/bash $USERNAME
sleep 1
passwd $USERNAME
sleep 1
pacman -S sudo grub-bios os-prober
sleep 1
EDITOR=vim visudo
sleep 1
vim /etc/default/grub
sleep 1
vim /etc/mkinitcpio.conf
sleep 1
mkinitcpio -p linux
sleep 1
grub-install --recheck $DRIVE
sleep 1
grub-mkconfig --output /boot/grub/grub.cfg
sleep 1
echo "exit"
echo "umount -R /mnt/boot"
echo "umount -R /mnt"
echo "cryptsetup close cryptroot"
