#!/bin/bash

source config

function createPartitions
{
  sgdisk --zap-all $DRIVE
  sleep 1
  sgdisk --clear \
         --new=1:0:+600MiB --typecode=1:ef00 --change-name=1:EFI \
         --new=2:0:0       --typecode=2:8300 --change-name=2:SYSTEM \
           $DRIVE
           
  sleep 1
  blkid /dev/sda2 >> config
  sleep 1
}

function setupEncryption
{
  modprobe dm-crypt
  sleep 1
  modprobe dm-mod
  sleep 1
  cryptsetup luksFormat -v -s 512 -h sha512 /dev/disk/by-partlabel/SYSTEM
  sleep 1
  cryptsetup --allow-discards --persistent open /dev/disk/by-partlabel/SYSTEM archsystem
  sleep 1
}

function setupFilesystemBtrfs
{
  # Init Filesystem
  mkfs.vfat -F32 /dev/disk/by-partlabel/EFI
  sleep 1
  if [ "$ENCRYPT_SYSTEM" = true ]; then
    SYSTEM_DRIVE=/dev/mapper/archsystem
  else
    SYSTEM_DRIVE=/dev/disk/by-partlabel/SYSTEM
  fi
  mkfs.btrfs -f -L archbtrfs $SYSTEM_DRIVE
  sleep 1
  mount $SYSTEM_DRIVE /mnt
  sleep 1
  
  # Mount Filesystem
  btrfs su cr /mnt/@
  sleep 1
  btrfs su cr /mnt/@home
  sleep 1
  btrfs su cr /mnt/@var
  sleep 1
  btrfs su cr /mnt/@snapshots
  sleep 1
  umount /mnt
  sleep 1
  mount -o noatime,compress=lzo,space_cache,subvol=@ $SYSTEM_DRIVE /mnt
  sleep 1
  mkdir -p /mnt/{home,var,.snapshots}
  sleep 1
  mount -o noatime,compress=lzo,space_cache,subvol=@home $SYSTEM_DRIVE /mnt/home
  sleep 1
  mount -o noatime,compress=lzo,space_cache,subvol=@var $SYSTEM_DRIVE /mnt/var
  sleep 1
  mount -o noatime,compress=lzo,space_cache,subvol=@snapshots $SYSTEM_DRIVE /mnt/.snapshots
  sleep 1
  mkdir /mnt/boot
  sleep 1
  mount /dev/disk/by-partlabel/EFI /mnt/boot
  sleep 1
}

function installSystem
{
  pacstrap /mnt base base-devel linux linux-headers linux-firmware vim curl btrfs-progs
  sleep 1
  genfstab -L /mnt >> /mnt/etc/fstab
  sleep 1
  vim /mnt/etc/fstab
  sleep 1
  curl -LJO tomasrejhons.github.io/malis/post-install
  sleep 1
  cp post-install /mnt/post-install
  sleep 1
  cp config /mnt/config
  sleep 1
  arch-chroot /mnt
}

createPartitions

if [ "$ENCRYPT_SYSTEM" = true ]; then
  setupEncryption
fi

setupFilesystemBtrfs
installSystem
